Question:
You’re given a 5x5 matrix of random integers between 1 and 50, representing data values for a set of rows and columns. Additionally, you have a 1D array of 5 elements, each of which represents a unique operation modifier for the columns in the matrix.
Your task is to perform the following conditional operation on each column of the matrix based on the values in the 1D array:<br>
1.If an element in the 1D array is even, Multiply each element in the corresponding column of the matrix by that value.<br>
2.If an element in the 1D array is odd, Add that value to each element in the corresponding column of the matrix.<br>

Steps:<br>
1.Start by generating a 5x5 matrix of random integers between 1 and 50.<br>
2.Create a 1D array of 5 integers (for this example, you can manually define these values).<br>
3.Apply the conditions specified above to modify each column of the matrix.<br><br>
Example:<br>
Suppose your 5x5 matrix and 1D array are as follows:<br>
<br>
1.5x5 Matrix:<br><br>
[[10, 15, 20, 25, 30],<br>[35, 40, 45, 50, 55],<br>[60, 65, 70, 75, 80],<br>[85, 90, 95, 100, 105],<br>[110, 115, 120, 125, 130]]

<br>
2.	1D Array: [2, 7, 4, 9, 6]<br><br>
Using the rules:<br>
•	Multiply each element in the first column by 2.<br>
•	Add 7 to each element in the second column.<br>
•	Multiply each element in the third column by 4.<br>
•	Add 9 to each element in the fourth column.<br>
•	Multiply each element in the fifth column by 6.<br><br>
Final Output<br>
Write a function to generate and display:<br>
•	The original matrix.<br>
•	The 1D array.<br>
•	The resulting matrix after applying the conditional operations.<br>


In [1]:
import numpy as np

# Step 1: Create a 5x5 matrix with random integers between 1 and 50
matrix = np.random.randint(1, 51, size=(5, 5))

# Step 2: Create a 1D array of 5 elements (for simplicity, let's choose some integers directly)
array_1d = np.array([2, 7, 4, 9, 6])

# Step 3: Initialize a result matrix to store the final output
result = np.copy(matrix)

# Step 4: Apply conditional operations based on even/odd values in the 1D array
for i in range(array_1d.size):
    if array_1d[i] % 2 == 0:
        # If element is even, multiply it with the corresponding column
        result[:, i] = matrix[:, i] * array_1d[i]
    else:
        # If element is odd, add it to the corresponding column
        result[:, i] = matrix[:, i] + array_1d[i]

# Display the results
print("Original 5x5 Matrix:\n", matrix)
print("\n1D Array for Operations:\n", array_1d)
print("\nResult after Conditional Broadcasting:\n", result)


Original 5x5 Matrix:
 [[23  1 29  8 47]
 [46 15  5  5  3]
 [27 24  4 39 34]
 [14 34 42 50 41]
 [12 12 30 34 24]]

1D Array for Operations:
 [2 7 4 9 6]

Result after Conditional Broadcasting:
 [[ 46   8 116  17 282]
 [ 92  22  20  14  18]
 [ 54  31  16  48 204]
 [ 28  41 168  59 246]
 [ 24  19 120  43 144]]
