# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] # To access the Value at Index 8

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Broadcasting 

NumPy Arrays Differ than Python Lists, because of their ability to broadcast!

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

This is called as broadcasting 

where 100 is brodcasted till the 5th index of the array

In [17]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_array = arr[0:6] # We took the slice of an array

In [20]:
slice_of_array # We printed that slice we took

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_array[:] # Taking everything from that slice

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_array[:] = 99 # Brodcasting the whole taken slice to 99

In [23]:
slice_of_array[:] # Printing that Boradcasted slice of array

array([99, 99, 99, 99, 99, 99])

In [24]:
arr #Now when We print the Original array the changes are made in Original Array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

***
In the Above Example,<br> 
• we created an array,<br>
• then we took a slice of that array in another variable,<br>
• we broadcasted that another variable into some other number,<br>
• this means all the values in the sliced variable got changed!<br>
• now when we print the Original Array, the changes are made in to the original   array

That means the Data is not copied to the another variable but it is just edited back to the original array

The reason NumPy does that, is to avoid  Memory Issues with very large arrays
***

If you Actually want to copy the array, instead of just editing in the same array, you can use .copy() function with the array,

Lets Understand this in the below example:

In [35]:
arr_copy = arr.copy() 

# We used .copy() function to copy the contents of array to a new Variable

In [29]:
arr # Printed the original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_copy # Printed the Copied Array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
arr_copy[:] = 100 # Broadcasting the copied array

In [32]:
arr_copy # Printing the new copied array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [33]:
arr # Printing the Original Array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

***

# Indexing and Selection of 2-D Arrays

In [36]:
import numpy as np

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

***
There are 2 different General Ways to grab contents from a 2-D Array

1) Double bracket format <br>
2) Comma Single bracket format
***

1) Double Bracket format

In [40]:
arr_2d[0][1]

10

above here, first bracket [0] is for row, and second [0] bracket is for column<br>
Note:- the number of Rows and Columns in NumPy arrays starts with zero 0<br>
Lets Try another Example below:-

In [43]:
arr_2d[1][2]

30

***

2) Comma Single Bracket format

In [44]:
arr_2d[0,1]

10

above here, in the Single Bracket [0,1], "0" is for Row and "1" is for Column <br>
Note:- the number of Rows and Columns in NumPy arrays starts with zero 0 <br>
Lets Try another Example below:-

In [45]:
arr_2d[1,2]

30

Note: It is recommended to use the Comma Single Bracket format in general, because it is less prone to errors
***

# Grabbing Sub-Matrices from a Matrix

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In the above Example, [:2,1:], ":2," means everything upto row 2, and then "1:" means grab column 1 onwards

Here, Basically ":2" is telling grab ---><br>
([[5, 10, 15]<br>
 &nbsp;[20, 25, 30]])
 
and "1:" is telling grab ---> <br>
([[10, 15]<br>
&nbsp;[25, 30]])

Now Lets execute and prove this:

In [52]:
arr_2d[:2] # This grabs the chunk of the 2 upper rows from the matrix

array([[ 5, 10, 15],
       [20, 25, 30]])

In [53]:
arr_2d[:2,1:] # This will grab the remaining chunk

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[1:3,:2] # Some Other Examples

array([[20, 25],
       [35, 40]])

Well most of the time, you might not use this kind of selection (grabbing sub sections of matrix), so if it is confusing you can focus less on this, but atleast you should know abt this also. <br> 
We usually grab a single element or a single row or column most of the time!

# Conditional Selection

In [70]:
arr = np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
bool_arr = arr > 5 # using comparision operator and storing in an array

In [74]:
bool_arr # this is called as a boolean array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr] # Printing the boolean array

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr>5] # doing the same job in one line

array([ 6,  7,  8,  9, 10])

Some Other Example

In [79]:
arr[arr < 3] # Example 1

array([1, 2])

In [82]:
arr[arr > 5] # Example 2

array([ 6,  7,  8,  9, 10])

Practice Program!

In [83]:
arr_2d = np.arange(50).reshape(5,10)

In [84]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Try getting different chunks of Sub-Matrices <br>
Write the Code Below: