# NumPy Operations

• <b>Array with Array</b> <br>
• <b>Array with Scalars</b> <br>
• <b>Universal array Functions</b>

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Array with Array

In [4]:
arr + arr # Adding 2 arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr # Subtracting 2 array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Array with Scalar

In [10]:
arr + 100 # Scalar Add

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
arr * 100 # Scalar Multiply

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [25]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [26]:
arr ** 2 # Power of 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# Error vs Warning in NumPy

In [22]:
1/0 # Error

ZeroDivisionError: division by zero

In [23]:
arr / arr #Warning (nan)

C:\Users\ashan\AppData\Local\Temp\ipykernel_12512\2753405767.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr #Warning


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [24]:
1 / arr # Warning (Infinity)

C:\Users\ashan\AppData\Local\Temp\ipykernel_12512\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

# Universal Array Functions

Numpy comes with many Universal Array Functions prebuilt, which you can use to perform different mathematical operations

In [28]:
np.sqrt(arr) # Square Root Function

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [30]:
np.exp(arr) # Exponent Function

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [33]:
np.max(arr) # Maximum Function for Arrays

10

In [35]:
arr.max() # Directly using max() Function on Arrays

10

In [37]:
np.sin(arr) # Sin Trigonometric function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

You can actually see more functions on this website:
[More NumPy Universal functions(Click Here)](https://numpy.org/doc/stable/reference/ufuncs.html)

***