# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr # 1-D Array or Vector

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat) # 2-D array or Matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np arange

In [8]:
np.arange(0,10) # Mostly used to create an Array using NumPy Library, this is the most commom way!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2) # here 3rd argument is the num of steps u want

array([ 0,  2,  4,  6,  8, 10])

# np zeros

In [10]:
np.zeros(3) # 1-D array of zeros by passing tuples

array([0., 0., 0.])

In [11]:
np.zeros((2,3)) # passing tuple of different dimension

array([[0., 0., 0.],
       [0., 0., 0.]])

# np ones

To create arrays of ones

Below Example is the example for single dimension arrays of 4 numbers

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# np Linspace

to make arrays with proper points difference


In [14]:
np.linspace(0,5,100) # Will give nums from 0 to 5 evenly spaces 100 points

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# np eye

 To Create Identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# np random

To create random number arrays

In [16]:
np.random.rand(5) # uniform Distribution from 0 to 1

array([0.82114172, 0.25262928, 0.06548478, 0.90950022, 0.63461844])

In [17]:
np.random.rand(2,5) # uniform distribution from 0 to 1 but in 2x5 matrix

array([[0.62618429, 0.15188493, 0.36581219, 0.78448587, 0.9468879 ],
       [0.32397579, 0.35352404, 0.98933729, 0.28315363, 0.70576659]])

In [18]:
np.random.randn(2) # Standarnd normal distribution

array([-0.0975608 , -0.22414609])

In [19]:
np.random.randn(2,4) # Standard  normal distribution of 2x4 matrix

array([[ 0.54788633, -1.30420279, -0.46773652,  2.0202759 ],
       [ 2.20282148, -0.04420972,  0.39528795, -1.2117009 ]])

In [20]:
np.random.randint(1,100)

58

In [21]:
np.random.randint(1,100,10)

array([ 9, 91, 34, 11, 98, 37, 49, 40, 28, 38])

# Some Usefull Attributes and Methods of an Array

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([ 7,  0, 38, 41, 24,  9, 45, 39, 14,  4])

# Reshape Method

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

arr.reshape(5,10) # This cant happen because I dont have enough numbers to fill this dimension array

This can be checked by multiplying both the numbers of the dimension in the array anf then checking how many numbers are thier in the main array

For Example:
in arr.reshape(5,5)
5 x 5 = 25
and in arr is the matrix of numbers from 0 to 24 which is exactly 25 numbers!
so we can say that yess this can happen because 25(5x5) = 25(0 to 24)

# Maximum Value in the Array

In [27]:
ranarr # Checking the RanArr Array

array([ 7,  0, 38, 41, 24,  9, 45, 39, 14,  4])

In [28]:
ranarr.max() # this max function will help you to find the maximum number from the array

45

In [29]:
ranarr.min() # opposite of max

0

In [30]:
ranarr.argmax() # will return the maximum values Index in the Array

6

In [31]:
ranarr.argmin() # Will return the mimimum values Index ion the Array

1

# Shape of the Vector

In [32]:
arr.shape

(25,)

"25," here "," is telling us it is 1-D vector!

In [33]:
arr = arr.reshape(5,5)

In [34]:
arr.shape

(5, 5)

# DataType of an Array

In [35]:
arr.dtype

dtype('int32')

# Directly using the Function

In [37]:
from numpy.random import randint

In [38]:
randint(2,10)

7